"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Save, Truck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

type Option = { id: string; label: string; detail: string };
type Props = { orderId: string; initialVehicleId?: string | null; initialPersonnelId?: string | null; initialDate?: string | Date | null; initialNotes?: string | null; initialStatus: string; compact?: boolean; onSaved?: () => void };

export default function DeliveryAssignment({ orderId, initialVehicleId, initialPersonnelId, initialDate, initialNotes, initialStatus, compact = false, onSaved }: Props) {
  const router = useRouter(); const [vehicles, setVehicles] = useState<Option[]>([]); const [personnel, setPersonnel] = useState<Option[]>([]); const [vehicleId, setVehicleId] = useState(initialVehicleId ?? ""); const [personnelId, setPersonnelId] = useState(initialPersonnelId ?? ""); const [date, setDate] = useState(initialDate ? new Date(initialDate).toISOString().slice(0, 10) : ""); const [notes, setNotes] = useState(initialNotes ?? ""); const [status, setStatus] = useState(initialStatus); const [loading, setLoading] = useState(false); const [loadingOptions, setLoadingOptions] = useState(true);
  useEffect(() => { Promise.all([fetch("/api/vehicles?pageSize=100&status=ACTIVE").then((r) => r.json()), fetch("/api/personnel?pageSize=100&status=ACTIVE").then((r) => r.json())]).then(([vehicleResult, personnelResult]) => { if (!vehicleResult.success || !personnelResult.success) throw new Error("Dağıtım seçenekleri yüklenemedi"); setVehicles(vehicleResult.data.data.map((v: { id: string; code: string; plate: string; type: string }) => ({ id: v.id, label: v.plate, detail: `${v.code} · ${v.type}` }))); setPersonnel(personnelResult.data.data.map((p: { id: string; fullName: string; employeeCode: string; phone: string }) => ({ id: p.id, label: p.fullName, detail: `${p.employeeCode} · ${p.phone}` }))); }).catch((error) => toast.error(error instanceof Error ? error.message : "Seçenekler yüklenemedi")).finally(() => setLoadingOptions(false)); }, []);
  async function save() { setLoading(true); try { const response = await fetch(`/api/orders/${orderId}/delivery`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vehicleId: vehicleId || null, personnelId: personnelId || null, deliveryDate: date, deliveryNotes: notes, status }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Dağıtım kaydedilemedi"); toast.success("Dağıtım bilgileri kaydedildi"); onSaved?.(); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Dağıtım kaydedilemedi"); } finally { setLoading(false); } }
  const selectClass = "h-9 w-full rounded-lg border border-input bg-background px-2.5 text-sm outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50";
  return <div className={compact ? "space-y-3" : "space-y-5"}>{!compact && <div><h2 className="text-lg font-semibold">Dağıtım Ataması</h2><p className="mt-1 text-sm text-muted-foreground">Siparişi aktif araç ve personele atayın.</p></div>}<div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1.5 text-sm font-medium"><span className="flex items-center gap-2"><Truck className="size-4 text-muted-foreground" /> Araç</span><select className={selectClass} value={vehicleId} onChange={(e) => setVehicleId(e.target.value)} disabled={loadingOptions || loading}><option value="">Araç seçilmedi</option>{vehicles.map((v) => <option key={v.id} value={v.id}>{v.label} · {v.detail}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium"><span className="flex items-center gap-2"><UserRound className="size-4 text-muted-foreground" /> Personel</span><select className={selectClass} value={personnelId} onChange={(e) => setPersonnelId(e.target.value)} disabled={loadingOptions || loading}><option value="">Personel seçilmedi</option>{personnel.map((p) => <option key={p.id} value={p.id}>{p.label} · {p.detail}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium">Dağıtım tarihi<input className={selectClass} type="date" value={date} onChange={(e) => setDate(e.target.value)} disabled={loading} /></label><label className="space-y-1.5 text-sm font-medium">Durum<select className={selectClass} value={status} onChange={(e) => setStatus(e.target.value)} disabled={loading}><option value="PENDING">Beklemede</option><option value="CONFIRMED">Onaylandı</option><option value="DELIVERING">Teslimatta</option><option value="DELIVERED">Teslim Edildi</option><option value="CANCELLED">İptal</option></select></label></div><label className="block space-y-1.5 text-sm font-medium">Dağıtım notu<textarea className="min-h-20 w-full rounded-lg border border-input bg-transparent px-3 py-2 text-sm outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50" value={notes} onChange={(e) => setNotes(e.target.value)} disabled={loading} placeholder="Teslimat için özel not..." /></label><Button className="w-full sm:w-auto" onClick={save} disabled={loading || loadingOptions}>{loading ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />} Kaydet</Button></div>;
}
