"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const steps = ["Firma bilgileri", "Logo yükleme", "Adres", "Telefon", "Vergi bilgileri", "İlk depo", "İlk araç", "İlk kullanıcı", "Tamamlandı"];
export default function OnboardingPage() {
  const router = useRouter(); const { update } = useSession(); const [step, setStep] = useState(1); const [form, setForm] = useState({ companyName: "", phone: "", address: "", taxNumber: "", logoUrl: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/onboarding").then((response) => response.json()).then((result) => { if (result.data) { setStep(result.data.onboardingStep ?? 1); setForm({ companyName: result.data.name ?? "", phone: result.data.phone ?? "", address: result.data.address ?? "", taxNumber: result.data.taxNumber ?? "", logoUrl: result.data.logoUrl ?? "" }); } }).finally(() => setLoading(false)); }, []);
  async function save(nextStep: number, completed = false) { setSaving(true); const response = await fetch("/api/onboarding", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, step: nextStep, completed }) }); setSaving(false); if (response.ok) { if (completed) { await update(); router.replace("/"); router.refresh(); } else setStep(nextStep); } }
  if (loading) return <main className="grid min-h-screen place-items-center">Kurulum yükleniyor...</main>;
  const activeStep = steps[step - 1];
  return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-3xl"><div className="rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-sm font-medium text-primary">İlk kurulum · {step}/9</p><h1 className="mt-2 text-3xl font-bold">{activeStep}</h1><div className="mt-6 flex gap-1">{steps.map((label, index) => <span key={label} title={label} className={`h-2 flex-1 rounded-full ${index + 1 <= step ? "bg-primary" : "bg-muted"}`} />)}</div><div className="mt-8 min-h-36">{step === 1 && <Input aria-label="Firma adı" placeholder="Firma adı" value={form.companyName} onChange={(event) => setForm({ ...form, companyName: event.target.value })} />}{step === 2 && <Input aria-label="Logo URL" placeholder="Logo URL" value={form.logoUrl} onChange={(event) => setForm({ ...form, logoUrl: event.target.value })} />}{step === 3 && <Textarea aria-label="Adres" placeholder="Firma adresi" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} />}{step === 4 && <Input aria-label="Telefon" placeholder="Telefon" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} />}{step === 5 && <Input aria-label="Vergi numarası" placeholder="Vergi numarası" value={form.taxNumber} onChange={(event) => setForm({ ...form, taxNumber: event.target.value })} />}{step > 5 && step < 9 && <div className="rounded-xl border border-dashed p-6 text-sm text-muted-foreground">Bu adım ERP içinden daha sonra tamamlanabilir.</div>}{step === 9 && <div className="rounded-xl bg-emerald-50 p-5 text-sm text-emerald-700">Kurulum tamamlandı. ERP’yi kullanmaya başlayabilirsiniz.</div>}</div><div className="mt-8 flex justify-between"><Button variant="outline" onClick={() => setStep((value) => Math.max(1, value - 1))} disabled={step === 1}>Geri</Button>{step === 9 ? <Button onClick={() => save(9, true)} disabled={saving}>ERP’ye başla</Button> : <div className="flex gap-2"><Button variant="ghost" onClick={() => save(9, true)}>Atla</Button><Button onClick={() => save(step + 1)} disabled={saving}>Devam et</Button></div>}</div></div></div></main>;
}
