"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Loader2, Save, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Personnel } from "@prisma/client";
import { createPersonnelSchema, type CreatePersonnelInput } from "../validators/personnel.schema";

export default function PersonnelForm({ initialData, mode }: { initialData?: Personnel; mode: "create" | "edit" }) {
  const router = useRouter(); const [isSubmitting, setIsSubmitting] = useState(false);
  const { register, handleSubmit, formState: { errors } } = useForm<CreatePersonnelInput>({ resolver: zodResolver(createPersonnelSchema), defaultValues: initialData ? { employeeCode: initialData.employeeCode, fullName: initialData.fullName, phone: initialData.phone, email: initialData.email ?? "", position: initialData.position, licenseNumber: initialData.licenseNumber ?? "", licenseClass: initialData.licenseClass ?? "", licenseExpiryDate: initialData.licenseExpiryDate ? new Date(initialData.licenseExpiryDate).toISOString().slice(0, 10) : "", hireDate: initialData.hireDate ? new Date(initialData.hireDate).toISOString().slice(0, 10) : "", status: initialData.status, notes: initialData.notes ?? "" } : { employeeCode: "", fullName: "", phone: "", email: "", position: "Kurye", licenseNumber: "", licenseClass: "", licenseExpiryDate: "", hireDate: "", status: "ACTIVE", notes: "" } });
  async function onSubmit(data: CreatePersonnelInput) { setIsSubmitting(true); try { const response = await fetch(mode === "edit" && initialData ? `/api/personnel/${initialData.id}` : "/api/personnel", { method: mode === "edit" ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "İşlem başarısız"); toast.success(mode === "edit" ? "Personel güncellendi" : "Personel oluşturuldu"); router.push(`/personnel/${result.data.id}`); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Bilinmeyen hata"); } finally { setIsSubmitting(false); } }
  const errorText = (field: keyof typeof errors) => errors[field]?.message?.toString();
  return <form onSubmit={handleSubmit(onSubmit)} className="space-y-8"><section className="rounded-xl border border-border/70 bg-card p-6"><h2 className="mb-6 text-lg font-semibold">Temel Bilgiler</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Personel Kodu" error={errorText("employeeCode")}><Input placeholder="PER-0001" {...register("employeeCode")} /></Field><Field label="Ad Soyad" error={errorText("fullName")}><Input placeholder="Ahmet Yılmaz" {...register("fullName")} /></Field><Field label="Telefon" error={errorText("phone")}><Input placeholder="0555 123 45 67" {...register("phone")} /></Field><Field label="E-posta" error={errorText("email")}><Input type="email" placeholder="ornek@email.com" {...register("email")} /></Field><Field label="Görev" error={errorText("position")}><Input placeholder="Kurye" {...register("position")} /></Field><Field label="Durum" error={errorText("status")}><select className="flex h-8 w-full rounded-lg border border-input bg-transparent px-2.5 text-sm" {...register("status")}><option value="ACTIVE">Aktif</option><option value="ON_LEAVE">İzinli</option><option value="INACTIVE">Pasif</option></select></Field></div></section><section className="rounded-xl border border-border/70 bg-card p-6"><h2 className="mb-6 text-lg font-semibold">Ehliyet ve Tarihler</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Ehliyet No" error={errorText("licenseNumber")}><Input {...register("licenseNumber")} /></Field><Field label="Ehliyet Sınıfı" error={errorText("licenseClass")}><Input placeholder="B" {...register("licenseClass")} /></Field><Field label="Ehliyet Geçerlilik" error={errorText("licenseExpiryDate")}><Input type="date" {...register("licenseExpiryDate")} /></Field><Field label="İşe Giriş Tarihi" error={errorText("hireDate")}><Input type="date" {...register("hireDate")} /></Field></div></section><section className="rounded-xl border border-border/70 bg-card p-6"><label htmlFor="personnel-notes" className="text-sm font-medium">Notlar</label><textarea id="personnel-notes" rows={4} className="mt-2 flex w-full rounded-lg border border-input bg-transparent px-3 py-2 text-sm focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50" {...register("notes")} /></section><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button className="w-full sm:w-auto" type="button" variant="outline" onClick={() => router.back()} disabled={isSubmitting}><X className="size-4" /> İptal</Button><Button className="w-full sm:w-auto" type="submit" disabled={isSubmitting}>{isSubmitting ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}{mode === "edit" ? "Güncelle" : "Oluştur"}</Button></div></form>;
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div className="space-y-1.5"><label className="text-sm font-medium">{label}</label>{children}{error && <p className="text-xs text-destructive">{error}</p>}</div>; }
