ALTER TABLE "Tenant" ADD COLUMN "plan" TEXT NOT NULL DEFAULT 'TRIAL';
ALTER TABLE "Tenant" ADD COLUMN "subscriptionStatus" TEXT NOT NULL DEFAULT 'TRIAL';
ALTER TABLE "Tenant" ADD COLUMN "trialEndsAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ADD COLUMN "billingStartsAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ADD COLUMN "lastPaymentAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ADD COLUMN "nextPaymentAt" TIMESTAMP(3);
ALTER TABLE "Tenant" ADD COLUMN "monthlyPrice" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "Tenant" ADD COLUMN "discountAmount" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "Tenant" ADD COLUMN "manualCharge" DECIMAL(14,2) NOT NULL DEFAULT 0;
