"use client";

import { useEffect, useState } from "react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { WalletCards, Fuel, Building2, AlertTriangle, type LucideIcon } from "lucide-react";

type Partner = { id: string; code: string; name: string; balance: number };
type Summary = { cashSales: number; ibanSales: number; totalSales: number; expenseTotal: number; expectedCash: number; dueEntries: { id: string; amount: string; dueDate: string | null; partner: { name: string } }[] };
const money = (value: number | string) => Number(value).toLocaleString("tr-TR", { style: "currency", currency: "TRY" });
const today = new Date().toISOString().slice(0, 10);

export default function FinancePage() {
  const [date, setDate] = useState(today); const [partners, setPartners] = useState<Partner[]>([]); const [summary, setSummary] = useState<Summary | null>(null); const [selectedPartner, setSelectedPartner] = useState(""); const [message, setMessage] = useState("");
  const [partner, setPartner] = useState({ code: "", name: "", paymentTermDays: "0" }); const [entry, setEntry] = useState({ type: "PURCHASE", amount: "", dueDate: date, notes: "" }); const [expense, setExpense] = useState({ category: "Yakıt", type: "FUEL", description: "Günlük yakıt", amount: "", expenseDate: date, paymentMethod: "CASH" });
  async function load() { const [p, s] = await Promise.all([fetch("/api/finance/partners"), fetch(`/api/finance/summary?date=${date}`)]); const pj = await p.json(); const sj = await s.json(); if (pj.success) setPartners(pj.data); if (sj.success) setSummary(sj.data); }
  // The effect synchronizes the selected date with the server-backed summary.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [date]);
  async function save(url: string, body: unknown) { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.error?.message ?? "İşlem başarısız"); setMessage("Kayıt başarıyla oluşturuldu."); await load(); }
  const submit = (action: () => Promise<void>) => async (event: React.FormEvent) => { event.preventDefault(); try { await action(); } catch (error) { setMessage(error instanceof Error ? error.message : "İşlem başarısız"); } };
  const metrics: Array<{ label: string; value: number; icon: LucideIcon }> = [{ label: "Nakit satış", value: summary?.cashSales ?? 0, icon: WalletCards }, { label: "IBAN satış", value: summary?.ibanSales ?? 0, icon: Building2 }, { label: "Toplam tahsilat", value: summary?.totalSales ?? 0, icon: WalletCards }, { label: "Toplam gider", value: summary?.expenseTotal ?? 0, icon: Fuel }, { label: "Beklenen kasa", value: summary?.expectedCash ?? 0, icon: WalletCards }];
  return <DashboardLayout><div className="space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Finans merkezi</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Kasa, bayi ve günlük sonuç</h1><p className="mt-1 text-sm text-muted-foreground">Nakit, IBAN, bayi cari hareketleri ve giderleri yönetin.</p></div><label className="text-sm font-medium">Gün<input type="date" className="mt-1 block rounded-lg border bg-background px-3 py-2" value={date} onChange={(e) => setDate(e.target.value)} /></label></header>{message && <p className="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</p>}
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{metrics.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-2xl border bg-card p-5"><Icon className="size-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{money(value)}</p></div>)}</section>
  <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">Bayi / ana bayi cari</h2><p className="mt-1 text-sm text-muted-foreground">Pozitif bakiye bayiye borcunuzu, negatif bakiye bayinin size borcunu gösterir.</p><div className="mt-4 grid gap-2">{partners.map((item) => <button type="button" key={item.id} onClick={() => setSelectedPartner(item.id)} className={`flex justify-between rounded-xl border p-3 text-left ${selectedPartner === item.id ? "border-primary bg-primary/5" : ""}`}><span><b>{item.name}</b><small className="ml-2 text-muted-foreground">{item.code}</small></span><b className={item.balance > 0 ? "text-amber-600" : "text-emerald-600"}>{money(item.balance)}</b></button>)}{!partners.length && <p className="rounded-xl bg-muted/40 p-4 text-sm text-muted-foreground">Henüz bayi kaydı yok.</p>}</div><form className="mt-5 grid gap-2 border-t pt-5 sm:grid-cols-3" onSubmit={submit(async () => { await save("/api/finance/partners", { ...partner, paymentTermDays: Number(partner.paymentTermDays), type: "BOTH" }); setPartner({ code: "", name: "", paymentTermDays: "0" }); })}><Input placeholder="Bayi kodu" value={partner.code} onChange={(e) => setPartner({ ...partner, code: e.target.value })} required /><Input placeholder="Bayi adı" value={partner.name} onChange={(e) => setPartner({ ...partner, name: e.target.value })} required /><Input type="number" min="0" placeholder="Vade gün" value={partner.paymentTermDays} onChange={(e) => setPartner({ ...partner, paymentTermDays: e.target.value })} /><Button className="sm:col-span-3">Bayi ekle</Button></form></section>
  <div className="space-y-6"><section className="rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">Bayi cari hareketi</h2><form className="mt-4 grid gap-3" onSubmit={submit(async () => { if (!selectedPartner) throw new Error("Önce bir bayi seçin."); await save(`/api/finance/partners/${selectedPartner}/ledger`, entry); setEntry({ ...entry, amount: "", notes: "" }); })}><select className="rounded-lg border bg-background px-3 py-2" value={entry.type} onChange={(e) => setEntry({ ...entry, type: e.target.value })}><option value="PURCHASE">Bayiden alış / borç</option><option value="SALE">Bayiye satış / alacak</option><option value="PAYMENT_TO_PARTNER">Bayie ödeme</option><option value="COLLECTION_FROM_PARTNER">Bayiden tahsilat</option><option value="ADJUSTMENT">Düzeltme</option></select><Input type="number" min="0.01" step="0.01" placeholder="Tutar (TL)" value={entry.amount} onChange={(e) => setEntry({ ...entry, amount: e.target.value })} required /><Input type="date" value={entry.dueDate} onChange={(e) => setEntry({ ...entry, dueDate: e.target.value })} /><Input placeholder="Açıklama" value={entry.notes} onChange={(e) => setEntry({ ...entry, notes: e.target.value })} /><Button>Cari hareketi kaydet</Button></form></section><section className="rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">Yakıt ve diğer gider</h2><form className="mt-4 grid gap-3" onSubmit={submit(async () => { await save("/api/finance/expenses", expense); setExpense({ ...expense, amount: "" }); })}><Input placeholder="Kategori" value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })} /><Input placeholder="Açıklama" value={expense.description} onChange={(e) => setExpense({ ...expense, description: e.target.value })} /><Input type="number" min="0.01" step="0.01" placeholder="Tutar (TL)" value={expense.amount} onChange={(e) => setExpense({ ...expense, amount: e.target.value })} required /><Button>Gideri kaydet</Button></form></section></div></div>
  <section className="rounded-2xl border border-amber-200 bg-amber-50/50 p-5"><div className="flex items-center gap-2"><AlertTriangle className="size-5 text-amber-600" /><h2 className="font-semibold">Yaklaşan bayi ödemeleri</h2></div>{summary?.dueEntries.length ? <div className="mt-3 grid gap-2">{summary.dueEntries.map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-white/70 px-3 py-2 text-sm"><span>{item.partner.name} · {item.dueDate ? new Date(item.dueDate).toLocaleDateString("tr-TR") : "Vadesiz"}</span><b>{money(item.amount)}</b></div>)}</div> : <p className="mt-2 text-sm text-muted-foreground">Seçilen gün için yaklaşan kayıt bulunmuyor.</p>}</section></div></DashboardLayout>;
}
