import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, CalendarDays, History, WalletCards } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";

const financeCards = [
  { title: "Cari Hesaplar", description: "Bayi hesaplarını, borç/alacak durumunu ve cari hareketleri yönetin.", href: "/finance/accounts", icon: BookOpen, accent: "from-cyan-500/20 to-blue-600/10", iconClass: "bg-cyan-500/15 text-cyan-700" },
  { title: "Finans Raporları", description: "Satış, tahsilat, gider ve yakıt verilerini tarih aralığıyla analiz edin.", href: "/finance/reports", icon: BarChart3, accent: "from-violet-500/20 to-fuchsia-600/10", iconClass: "bg-violet-500/15 text-violet-700" },
  { title: "Günlük Bayi Özeti", description: "Günlük bayi satışlarını IBAN, nakit ve POS kırılımıyla görüntüleyin.", href: "/finance/daily", icon: CalendarDays, accent: "from-emerald-500/20 to-teal-600/10", iconClass: "bg-emerald-500/15 text-emerald-700" },
  { title: "Geçmiş Rotalar", description: "Tamamlanan rota ve teslimat geçmişini tarih ve ekip bazında inceleyin.", href: "/route-histories", icon: History, accent: "from-amber-500/20 to-orange-600/10", iconClass: "bg-amber-500/15 text-amber-700" },
];

export default function FinanceHubPage() {
  return <DashboardLayout><div className="space-y-8"><header className="max-w-2xl"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><WalletCards className="size-5" /></span><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Finans merkezi</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Finans işlemleri</h1></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Cari hesaplarınızı, finansal raporlarınızı ve operasyon geçmişinizi tek merkezden yönetin. Devam etmek için aşağıdaki çalışma alanlarından birini seçin.</p></header><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4" aria-label="Finans çalışma alanları">{financeCards.map(({ title, description, href, icon: Icon, accent, iconClass }) => <Link key={href} href={href} className={`group relative overflow-hidden rounded-3xl border border-border/70 bg-gradient-to-br ${accent} bg-card p-6 shadow-sm transition-all duration-200 hover:-translate-y-1 hover:border-primary/35 hover:shadow-xl focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50`}><div className="flex items-start justify-between gap-4"><span className={`grid size-12 place-items-center rounded-2xl ${iconClass}`}><Icon className="size-6" /></span><ArrowRight className="size-5 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></div><h2 className="mt-8 text-xl font-bold tracking-tight">{title}</h2><p className="mt-2 min-h-12 text-sm leading-5 text-muted-foreground">{description}</p><span className="mt-6 inline-flex text-sm font-semibold text-primary">Çalışma alanını aç <ArrowRight className="ml-1.5 size-4" /></span></Link>)}</section></div></DashboardLayout>;
}
