import Link from "next/link";
import { Building2, ShieldCheck } from "lucide-react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { requirePermission } from "@/server/auth/authorization";
import { getPlatformDashboardSummary, listPlatformTenants } from "@/features/platform/services/tenant.service";
import PlatformTenantActions from "@/features/platform/components/PlatformTenantActions";
import ImpersonateTenantButton from "@/features/platform/components/ImpersonateTenantButton";

export default async function PlatformPage() {
  await requirePermission("platform.view");
  const [tenants, summary] = await Promise.all([listPlatformTenants(), getPlatformDashboardSummary()]);
  const metrics = [["Toplam tenant", summary.tenantCount], ["Aktif tenant", summary.activeTenants], ["Pasif tenant", summary.passiveTenants], ["Trial tenant", summary.trialTenants], ["Bu ay yeni tenant", summary.newTenants], ["Toplam kullanıcı", summary.totalUsers], ["Toplam sipariş", summary.totalOrders], ["Toplam ciro", summary.totalRevenue.toLocaleString("tr-TR", { style: "currency", currency: "TRY" })], ["MRR / ARR", `${summary.mrr.toLocaleString("tr-TR", { style: "currency", currency: "TRY" })} / ${summary.arr.toLocaleString("tr-TR", { style: "currency", currency: "TRY" })}`]] as const;
   return <DashboardLayout><div className="space-y-6"><div><p className="flex items-center gap-2 text-sm font-medium text-primary"><ShieldCheck className="size-4" /> Global yönetim</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Platform Merkezi</h1><p className="mt-2 text-sm text-muted-foreground">METLAS ERP SaaS tenant, lisans, paket ve sistem yönetimi.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/platform/subscriptions" className="rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted">Abonelikler</Link><Link href="/platform/packages" className="rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted">Paketler</Link><Link href="/platform/invoices" className="rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted">Faturalar</Link><Link href="/platform/payments" className="rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted">Ödemeler</Link><Link href="/platform/settings" className="rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted">Sistem Ayarları</Link></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(([label, value]) => <div key={label} className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-bold tabular-nums">{value}</p></div>)}</div><div className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><h2 className="font-semibold">Yeni tenant</h2><p className="mt-1 text-sm text-muted-foreground">Yeni tenant oluşturulduğunda temel onboarding akışı başlatılır.</p><div className="mt-4"><PlatformTenantActions /></div></div><div className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Building2 className="size-5 text-primary" /><h2 className="font-semibold">Tenantlar</h2></div><div className="mt-4 divide-y divide-border/70">{tenants.map((tenant) => <div key={tenant.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="font-medium">{tenant.name}</p><p className="text-xs text-muted-foreground">{tenant.slug} · {tenant._count.users} kullanıcı · {tenant._count.customers} müşteri · {tenant._count.orders} sipariş</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-100 px-2 py-1 text-xs font-medium text-blue-700">{tenant.plan}</span><span className={`rounded-full px-2 py-1 text-xs ${tenant.isActive ? "bg-emerald-100 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{tenant.isActive ? "Aktif" : "Pasif"}</span><ImpersonateTenantButton tenantId={tenant.id} /><PlatformTenantActions tenantId={tenant.id} isActive={tenant.isActive} /></div></div>)}</div></div></div></DashboardLayout>;
}
