"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Input } from "@/components/ui/input";
import Pagination from "@/shared/components/pagination";

type AuditRow = { id: string; action: string; entityType: string; entityId: string; tenantId: string | null; actorRole: string | null; ipAddress: string | null; browser: string | null; operatingSystem: string | null; url: string | null; httpMethod: string | null; oldData: unknown; newData: unknown; createdAt: string; actor: { name: string; email: string } | null; tenant: { name: string } | null };
const labels: Record<string, string> = { IMPERSONATION_START: "Impersonation başladı", IMPERSONATION_END: "Impersonation bitti", PACKAGE_CREATE: "Paket oluşturuldu", SUBSCRIPTION_UPDATE: "Abonelik güncellendi", INVOICE_CREATE: "Fatura oluşturuldu", PAYMENT_CREATE: "Ödeme oluşturuldu", PAYMENT_REFUND: "Ödeme iade edildi" };

export default function PlatformAuditLogList() {
  const [items, setItems] = useState<AuditRow[]>([]); const [entityType, setEntityType] = useState(""); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
  useEffect(() => { const controller = new AbortController(); const query = new URLSearchParams({ page: String(page), pageSize: "25" }); if (entityType) query.set("entityType", entityType); fetch(`/api/platform/audit-logs?${query}`, { signal: controller.signal }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? "Platform audit kayıtları yüklenemedi"); setItems(result.data.data); setTotalPages(result.data.totalPages ?? 1); }).catch((error) => { if (error.name !== "AbortError") toast.error(error.message); }); return () => controller.abort(); }, [entityType, page]);
  return <div className="space-y-5"><Input value={entityType} onChange={(event) => { setEntityType(event.target.value); setPage(1); }} placeholder="Entity türü ara: Tenant, Order, Payment..." />{items.length === 0 ? <div className="rounded-2xl border border-dashed border-border/70 bg-card p-10 text-center text-sm text-muted-foreground">Platform audit kaydı bulunamadı.</div> : <div className="overflow-x-auto rounded-2xl border border-border/70 bg-card"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b text-left text-xs uppercase tracking-wide text-muted-foreground"><th className="p-4">İşlem</th><th className="p-4">Aktör</th><th className="p-4">Tenant</th><th className="p-4">İstek</th><th className="p-4">Cihaz</th><th className="p-4">Tarih</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-4"><p className="font-medium">{labels[item.action] ?? item.action}</p><p className="text-xs text-muted-foreground">{item.entityType} · {item.entityId}</p></td><td className="p-4">{item.actor?.name ?? "Sistem"}<p className="text-xs text-muted-foreground">{item.actorRole ?? item.actor?.email ?? "-"}</p></td><td className="p-4">{item.tenant?.name ?? "Global"}</td><td className="p-4 text-xs">{item.httpMethod ?? "-"} {item.url ?? "-"}<br />{item.ipAddress ?? "IP yok"}</td><td className="p-4 text-xs">{item.browser ?? "-"}<br />{item.operatingSystem ?? "-"}</td><td className="p-4 text-xs">{new Date(item.createdAt).toLocaleString("tr-TR")}</td></tr>)}</tbody></table></div>}<Pagination page={page} totalPages={totalPages} onChange={setPage} /></div>;
}
