import Link from "next/link";
import { ArrowLeft, Edit, Gauge, Truck } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Vehicle } from "@prisma/client";

const statusLabels: Record<string, string> = { ACTIVE: "Aktif", MAINTENANCE: "Bakımda", INACTIVE: "Pasif" };
const statusStyles: Record<string, string> = { ACTIVE: "bg-emerald-50 text-emerald-700", MAINTENANCE: "bg-amber-50 text-amber-700", INACTIVE: "bg-muted text-muted-foreground" };

export default function VehicleDetail({ vehicle }: { vehicle: Vehicle }) {
  return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" render={<Link href="/vehicles" />}><ArrowLeft className="size-4" /></Button><div className="min-w-0"><h1 className="truncate text-2xl font-bold tracking-tight">{vehicle.plate}</h1><p className="font-mono text-xs text-muted-foreground">{vehicle.code}</p></div></div><Button className="w-full md:w-auto" variant="outline" render={<Link href={`/vehicles/${vehicle.id}/edit`} />}><Edit className="size-4" /> Düzenle</Button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Durum" value={statusLabels[vehicle.status] ?? vehicle.status} tone={statusStyles[vehicle.status]} /><Stat label="Araç Tipi" value={vehicle.type} /><Stat label="Kapasite" value={`${vehicle.capacity} ${vehicle.capacityUnit}`} /><Stat label="Kilometre" value={`${vehicle.mileage.toLocaleString("tr-TR")} km`} /></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-border/70 bg-card p-6"><h2 className="mb-5 flex items-center gap-2 text-lg font-semibold"><Truck className="size-5 text-primary" /> Araç Bilgileri</h2><div className="grid gap-4 sm:grid-cols-2"><Info label="Marka" value={vehicle.brand} /><Info label="Model" value={vehicle.model} /><Info label="Model Yılı" value={vehicle.modelYear?.toString()} /><Info label="Kapasite Birimi" value={vehicle.capacityUnit} /></div></section><section className="rounded-xl border border-border/70 bg-card p-6"><h2 className="mb-5 flex items-center gap-2 text-lg font-semibold"><Gauge className="size-5 text-primary" /> Belge Takibi</h2><div className="grid gap-4 sm:grid-cols-2"><Info label="Muayene Tarihi" value={vehicle.inspectionDate ? new Date(vehicle.inspectionDate).toLocaleDateString("tr-TR") : "Belirtilmedi"} /><Info label="Sigorta Tarihi" value={vehicle.insuranceDate ? new Date(vehicle.insuranceDate).toLocaleDateString("tr-TR") : "Belirtilmedi"} /></div></section></div>{vehicle.notes && <section className="rounded-xl border border-border/70 bg-card p-6"><h2 className="mb-3 text-lg font-semibold">Notlar</h2><p className="whitespace-pre-wrap text-sm text-muted-foreground">{vehicle.notes}</p></section>}</div>;
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className="rounded-xl border border-border/70 bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className={`mt-2 inline-flex rounded-full px-2 py-1 text-base font-bold ${tone ?? ""}`}>{value}</p></div>; }
function Info({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value || "-"}</p></div>; }
